name: Build testing

on:
  push: #for testing
    branches:
      - main

jobs:
  testing:
    name: Build test

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: build gradle
      run: ./gradlew build
