name: Building

on:
  pull_request: #for testing
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Validate Gradle wrapper binaries
      uses: gradle/wrapper-validation-action@v1

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build with Gradle Wrapper
      run: ./gradlew build
