
name: Kotlin and Android Lint Check

on:
  push:
    branches:
      - main

jobs:
  testing:
    name: Lint Check

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3.13.0
      with:
        java-version: 17
    - name: Cache Gradle Dependencies
      uses: actions/cache@v2
      with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
    - name: Run Kotlin Linter
      run: ./gradlew ktlintStagingDebugCheck

    - name: Run Android Linter
      run: ./gradlew lintStagingDebug
