name: Lint Checking

on:
  pull_request: #for testing
    branches:
      - main

jobs:
  testing:
    name: Lint Check

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Run Kotlin Linter
      run: ./gradlew ktlintCheck

    - name: Fix Ktlint issues
      run: ./gradlew ktlintFormat

      
    #- name: Run Android Linter
     # run: ./gradlew lintStagingDebug
