
name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Lint Check

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17

    - name: Run Kotlin Linter
      run: ./gradlew ktlintStagingDebugCheck

    - name: Run Android Linter
      run: ./gradlew lintStagingDebug
