name: Kotlin and Android Lint Check

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Cache Gradle Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make Gradlew Executable
        run: chmod +x gradlew

      - name: Use the correct Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 7.2

      - name: Run Linters
        run: ./gradlew ktlint lintStagingDebug
