name: Lint Checking

on:
  push: #for testing
    branches:
      - main

jobs:
  testing:
    name: Lint Check

    runs-on: ubuntu-latest

    steps:
    - name: Clone Repo
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    #- name: Run Kotlin Linter
     # run: ./gradlew ktlintStagingDebugCheck removing this job until everything else works

    - name: Run Android Linter
      run: ./gradlew lintStagingDebug
